// <auto-generated />
namespace Quiz_August6_KyleElyk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixedToppingPrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedToppingPrice));
        
        string IMigrationMetadata.Id
        {
            get { return "201908061951089_fixedToppingPrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
